spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:54320/postgres
    username: postgres
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
